const RouteWatcher = '@/components/PageTab/RouteWatcher';
export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user',
        routes: [
          {
            name: 'login',
            path: '/user/login',
            component: './user/login',
          },
        ],
      },
    ],
  },
  {
    path: '/',
    redirect: '/dashboard',
  },
  {
    path: '/',
    // redirect: '/dashboard',
    component: '@/components/PageTab/TabLayout',
    flatMenu: true, // lift sub-routes up to top
    routes: [
      {
        path: '/dashboard',
        name: '首页',
        icon: 'smile',
        access: 'menuFilter',
        menuCode: '100',
        component: './dashboard',
        wrappers: [RouteWatcher],
      },
      {
        path: '/member',
        name: '会员管理',
        icon: 'crown',
        access: 'menuFilter',
        routes: [
          {
            path: '/member/personal',
            name: '个人会员',
            icon: 'smile',
            access: 'menuFilter',
            component: './member/personal',
            wrappers: [RouteWatcher],
          },
          {
            path: '/member/business',
            name: '企业会员',
            icon: 'smile',
            access: 'menuFilter',
            component: './member/business',
            wrappers: [RouteWatcher],
          },
          {
            path: '/member/access-provider',
            name: '接入商',
            icon: 'smile',
            access: 'menuFilter',
            component: './member/access-provider',
            wrappers: [RouteWatcher],
          },
        ],
      },
      {
        path: '/account',
        name: '账户管理',
        icon: 'crown',
        access: 'menuFilter',
        menuCode: '102',
        // component: './Admin',
        routes: [
          {
            path: '/account/business',
            name: '企业账户',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10202',
            component: './account/business',
            wrappers: [RouteWatcher],
          },
          {
            path: '/account/personal',
            name: '个人账户',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10201',
            component: './account/personal',
            wrappers: [RouteWatcher],
          },
        ],
      },
      {
        path: '/trade',
        name: '交易管理',
        icon: 'crown',
        access: 'menuFilter',
        menuCode: '103',
        // component: './Admin',
        routes: [
          {
            path: '/trade/business/cash-out',
            name: '企业提现',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10301',
            component: './trade/business/cash-out',
            wrappers: [RouteWatcher],
          },
          {
            path: '/trade/business/recharge',
            name: '企业充值',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10302',
            component: './trade/business/recharge',
            wrappers: [RouteWatcher],
          },
          {
            path: '/trade/personal/cash-out',
            name: '个人提现',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10303',
            component: './trade/personal/cash-out',
            wrappers: [RouteWatcher],
          },
          {
            path: '/trade/order/pay-by-other',
            name: '代付订单',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10304',
            component: './trade/order/pay-by-other',
            wrappers: [RouteWatcher],
          },
          {
            path: '/trade/order/salary',
            name: '薪资订单',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10305',
            component: './trade/order/salary',
            wrappers: [RouteWatcher],
          },
          {
            path: '/trade/order/refunds',
            name: '退款订单',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10306',
            component: './trade/order/refunds',
            wrappers: [RouteWatcher],
          },
        ],
      },
      {
        path: '/access',
        name: '通道管理',
        icon: 'crown',
        access: 'menuFilter',
        menuCode: '105',
        // component: './Admin',
        routes: [
          {
            path: '/access/list',
            name: '通道列表',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10501',
            component: './access/list',
            wrappers: [RouteWatcher],
          },
        ],
      },
      {
        path: '/report',
        name: '报表管理',
        icon: 'crown',
        access: 'menuFilter',
        menuCode: '104',
        // component: './Admin',
        routes: [
          {
            path: '/report/check',
            name: '对账单',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10401',
            component: './report/check',
            wrappers: [RouteWatcher],
          },
        ],
      },
      {
        path: '/system',
        name: '系统管理',
        icon: 'crown',
        access: 'menuFilter',
        menuCode: '106',
        routes: [
          {
            path: '/system/user-list',
            name: '用户列表',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10601',
            component: './system/user-list',
            wrappers: [RouteWatcher],
          },
          {
            path: '/system/role-list',
            name: '角色列表',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10602',
            component: './system/role-list',
            wrappers: [RouteWatcher],
          },
          {
            path: '/system/user-log',
            name: '用户日志',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10603',
            component: './system/user-log',
            wrappers: [RouteWatcher],
          },
          {
            path: '/system/setting',
            name: '系统配置',
            icon: 'smile',
            access: 'menuFilter',
            menuCode: '10604',
            component: './system/setting',
            wrappers: [RouteWatcher],
          },
        ],
      },
    ],
  },
  // {
  //   name: 'list.table-list',
  //   icon: 'table',
  //   path: '/list',
  //   component: './ListTableList',
  // },
  {
    component: './404',
  },
];
